#!/usr/bin/env bash
#------------------------------------------------------------------
#---Added extra PATH (needed for cron :-()
export PATH=${PATH}:/usr/sbin

#---Setup compiler-------------------------------------------------
#export CXX=clang++
#export CC=clang

#---Parameters-----------------------------------------------------
THIS=$(dirname $0)
export ExtraCMakeOptions=";-Droofit=ON;-Dmysql=OFF"

#---Run the CTest script-------------------------------------------
ctest -V -S ${THIS}/root-build.cmake



