#!/usr/bin/env bash
#------------------------------------------------------------------
#---Added extre PATH (needed for cron :-()
export PATH=${PATH}:/usr/sbin

#---Setup compiler-------------------------------------------------
export CXX=g++
export CC=gcc

#---Parameters-----------------------------------------------------
THIS=$(dirname $0)
export ExtraCMakeOptions=";-Droofit=ON"

#---Run the CTest script-------------------------------------------
ctest -V -S ${THIS}/root-build.cmake



