#!/usr/bin/env bash
set -e
set -x
THIS=$(dirname $0)

echo source $THIS/jk-setup.sh $LABEL $COMPILER $BUILDTYPE $EXTERNALS
source $THIS/jk-setup.sh $LABEL $COMPILER $BUILDTYPE $EXTERNALS

echo "Dumping the full environment ---------------------------------------------------------"
env | sort | sed 's/:/:?     /g' | tr '?' '\n'
echo "--------------------------------------------------------------------------------------"

#---Create stampfile to enable our jenkins to purge old builds------------------------------
touch $WORKSPACE/controlfile

#---Run the CTest script depending on the compiler------------------------------------------
if [[ $COMPILER == *classic* ]]
then

    ctest -V -S ${THIS}/root-classic.cmake
    status=$?

else

    ctest -VV -S ${THIS}/root-build.cmake
    status=$?

    # do not run the tests if continous build fails
    if [ $status -ne 0 ] && [ "$MODE" = continuous ]; then
       exit $status
    fi

    ctest -V -S ${THIS}/root-test.cmake
    status=$?

fi

exit $status


