#!/usr/bin/env bash

export LC_CTYPE=en_US.UTF-8
export LC_ALL=en_US.UTF-8
export EXTERNALDIR=/afs/cern.ch/sw/lcg/app/releases/ROOT-externals/
THIS=$(dirname $0)

if [[ $COMPILER == *gcc* ]]
then
    export PATH=/afs/cern.ch/sw/lcg/contrib/CMake/3.0.0/Linux-i386/bin:${PATH}
    ARCH=$(uname -m)
    . /afs/cern.ch/sw/lcg/contrib/gcc/4.9.0/${ARCH}-${LABEL}/setup.sh
    export FC=gfortran
    export CXX=`which g++`
    export CC=`which gcc`

    perl ${EXTERNALDIR}${EXTERNALS}/setup.pl -l ${LABEL} -c ${COMPILER} -v opt -t ${EXTERNALS}  
    eval $(${EXTERNALDIR}${EXTERNALS}/setup.pl -l ${LABEL} -c ${COMPILER} -v opt -t ${EXTERNALS})
    export ExtraCMakeOptions=";-Droofit=ON;-Dchirp=OFF;-Dhdfs=OFF;-Dbonjour=OFF;-Dfail-on-missing=ON"

elif [[ $COMPILER == *native* ]]
then
    export ExtraCMakeOptions=";-Dfortran=OFF"

elif [[ $COMPILER == *classic* ]]
then
    if [ "${LABEL}" == "slc6" ]; then
        export PATH=/afs/cern.ch/sw/lcg/contrib/CMake/3.0.0/Linux-i386/bin:${PATH}
    fi

elif [[ $COMPILER == *icc* ]]
then
    export PATH=/afs/cern.ch/sw/lcg/contrib/CMake/3.0.0/Linux-i386/bin:${PATH}
    . /afs/cern.ch/sw/IntelSoftware/linux/setup.sh
    . /afs/cern.ch/sw/IntelSoftware/linux/x86_64/xe2013/bin/ifortvars.sh intel64
    . /afs/cern.ch/sw/IntelSoftware/linux/x86_64/xe2013/bin/iccvars.sh intel64
    export CC=icc
    export CXX=icc
    export FC=ifort
    
    perl ${EXTERNALDIR}${EXTERNALS}/setup.pl -l ${LABEL} -c ${COMPILER} -v opt -t ${EXTERNALS}  
    eval $(${EXTERNALDIR}${EXTERNALS}/setup.pl -l ${LABEL} -c ${COMPILER} -v opt -t ${EXTERNALS})
    export ExtraCMakeOptions=""

fi


#---Run the CTest script depending on the compiler------------------------------------------
if [[ $COMPILER == *classic* ]]
then
    ctest -V -S ${THIS}/root-classic.cmake
else
    ctest -V -S ${THIS}/root-build.cmake
fi

