#!/usr/bin/env bash

# This script prepares the environment to run ROOT tests using the devX
# nightlies of the day before built for slc6 on a cc7 node.

export LC_CTYPE=en_US.UTF-8
export LC_ALL=en_US.UTF-8
THIS=$(dirname $0)

V_TYPE=opt

export LABEL_ORG=${LABEL}

if [ "${DAY}" == "yesterday" ]
then
    DAY=$(date --date="yesterday"|awk '{print $1}')
fi

if [ "${DAY}" == "today" ]
then
    DAY=$(date |awk '{print $1}')
fi


echo "**************************** ${DAY}"

if [ "${LABEL_ORG}" == "slc7" ]
then
    LABEL=slc6
fi

if [ "${LABEL}" == "slc6" ] 
then
    export EXTERNALDIR=/afs/cern.ch/sw/lcg/app/releases/ROOT-externals/
    if [ "${LABEL_ORG}" == "slc6" ]
    then

# We need Cmake for 64b machines in order to work in CentOs7 (SPI-741 bug)
	export PATH=/afs/cern.ch/sw/lcg/contrib/CMake/2.8.9/Linux-i386/bin:${PATH}
    fi
else
    export EXTERNALDIR=$HOME/ROOT-externals/
fi

if [[ $COMPILER == *gcc* ]]
then
    gcc48version=4.8
    gcc49version=4.9
    COMPILERversion=${COMPILER}version

    ARCH=$(uname -m)

    # Here we setup ROOT and its environment (qt, gfal, gsl, davix ...)
    baseROOTDir=/afs/cern.ch/sw/lcg/app/nightlies/${lcg_target}/${DAY}/ROOT/${VERSION}/${ARCH}-${LABEL}-${COMPILER}-${V_TYPE}

    . ${baseROOTDir}/ROOT-env.sh
    . ${baseROOTDir}/bin/thisroot.sh

    if [ -d roottest ];
    then 
        (cd roottest && git pull); 
    else 
        (git clone http://roottest.cern.ch && cd roottest && git checkout ${VERSION})
    fi
fi    

echo "Dumping the full environment ---------------------------------------------------------"
env | sort | sed 's/:/:?     /g' | tr '?' '\n'
echo "--------------------------------------------------------------------------------------"

#---Run the CTest script depending on the compiler------------------------------------------
ctest -V -S ${THIS}/root-test-slc7_2.cmake

exit 0


