#!/usr/bin/env bash

export LC_CTYPE=en_US.UTF-8
export LC_ALL=en_US.UTF-8
THIS=$(dirname $0)

if [ "${BUILDTYPE}" == "Debug" ]
then
    VERSION=dbg
else
    VERSION=opt
fi

if [ "${LABEL}" == "slc6" ] 
then
    export EXTERNALDIR=/afs/cern.ch/sw/lcg/app/releases/ROOT-externals/
    export PATH=/afs/cern.ch/sw/lcg/contrib/CMake/3.0.0/Linux-i386/bin:${PATH}
else
    export EXTERNALDIR=$HOME/ROOT-externals/
fi

if [[ $COMPILER == *gcc* ]]
then
    gcc47version=4.7
    gcc48version=4.8
    gcc49version=4.9
    COMPILERversion=${COMPILER}version

    ARCH=$(uname -m)
    . /afs/cern.ch/sw/lcg/contrib/gcc/${!COMPILERversion}/${ARCH}-${LABEL}/setup.sh
    export FC=gfortran
    export CXX=`which g++`
    export CC=`which gcc`

    cmdout=`ls ${EXTERNALDIR}${EXTERNALS} | grep ${LABEL} | grep ${COMPILER} | grep ${VERSION}`
    if [ $? -eq 0 ];then
	source ${EXTERNALDIR}${EXTERNALS}/setup.sh -c ${COMPILER} -v ${VERSION}
    else
	eval $(${EXTERNALDIR}${EXTERNALS}/setup.pl -l ${LABEL} -c ${COMPILER} -v ${VERSION} -t ${EXTERNALS})
    fi
    export ExtraCMakeOptions="-Dchirp=OFF -Dhdfs=OFF -Dbonjour=OFF -Dfail-on-missing=ON ${ExtraCMakeOptions}"

elif [[ $COMPILER == *clang* ]]
then
    clang34version=3.4
    clang35version=3.5
    clang36version=3.6
    COMPILERversion=${COMPILER}version
    clang34gcc=48
    clang35gcc=49
    GCCversion=${COMPILER}gcc

    ARCH=$(uname -m)
    . /afs/cern.ch/sw/lcg/external/llvm/${!COMPILERversion}/${ARCH}-slc6/setup.sh
    export CC=`which clang`
    export CXX=`which clang++`
    cmdout=`ls ${EXTERNALDIR}${EXTERNALS} | grep ${LABEL} | grep ${COMPILER} | grep ${VERSION}`
    if [ $? -eq 0 ];then
	source ${EXTERNALDIR}${EXTERNALS}/setup.sh -c ${COMPILER} -v ${VERSION}
    else
	eval $(${EXTERNALDIR}${EXTERNALS}/setup.pl -l ${LABEL} -c ${!GCCversion} -v ${VERSION} -t ${EXTERNALS})
    fi
    export ExtraCMakeOptions="${ExtraCMakeOptions} -Dfortran=OFF -Dgcctoolchain=$(dirname $(dirname `which gcc`))"

elif [[ $COMPILER == *native* ]]
then
    cmdout=`ls ${EXTERNALDIR}${EXTERNALS} | grep ${LABEL} | grep ${COMPILER} | grep ${VERSION}`
    if [ $? -eq 0 ];then
	source ${EXTERNALDIR}${EXTERNALS}/setup.sh -c ${COMPILER} -v ${VERSION}
    else
	eval $(${EXTERNALDIR}${EXTERNALS}/setup.pl -l ${LABEL} -c native -v ${VERSION} -t ${EXTERNALS})
    fi
    export ExtraCMakeOptions="-Dfortran=OFF ${ExtraCMakeOptions}"

elif [[ $COMPILER == *classic* ]]
then
    cmdout=`ls ${EXTERNALDIR}${EXTERNALS} | grep ${LABEL} | grep ${COMPILER} | grep ${VERSION}`
    if [ $? -eq 0 ];then
	source ${EXTERNALDIR}${EXTERNALS}/setup.sh -c ${COMPILER} -v ${VERSION}
    else
	eval $(${EXTERNALDIR}${EXTERNALS}/setup.pl -l ${LABEL} -c native -v ${VERSION} -t ${EXTERNALS})
    fi
elif [[ $COMPILER == *icc* ]]
then
    . /afs/cern.ch/sw/IntelSoftware/linux/setup.sh
    . /afs/cern.ch/sw/IntelSoftware/linux/x86_64/xe2013/bin/ifortvars.sh intel64
    . /afs/cern.ch/sw/IntelSoftware/linux/x86_64/xe2013/bin/iccvars.sh intel64
    export CC=icc
    export CXX=icc
    export FC=ifort
fi

echo "Dumping the full environment ---------------------------------------------------------"
env | sort | sed 's/:/:?     /g' | tr '?' '\n'
echo "--------------------------------------------------------------------------------------"

#---Run the CTest script depending on the compiler------------------------------------------
if [[ $COMPILER == *classic* ]]
then
    ctest -VV -S ${THIS}/root-classic.cmake
    build_rc=$?
    ctest -V -S ${THIS}/root-test-classic.cmake
else
    ctest -VV -S ${THIS}/root-build.cmake
    build_rc=$?
    ctest -V -S ${THIS}/root-test.cmake
fi

exit $build_rc


