#!/usr/bin/env bash

export LC_CTYPE=en_US.UTF-8
export LC_ALL=en_US.UTF-8
THIS=$(dirname $0)

V_TYPE=opt

export LABEL_ORG=${LABEL}

if [ "${LABEL_ORG}" == "slc7" ]
then
    LABEL=slc6
fi

if [ "${LABEL}" == "slc6" ] 
then
    
    export EXTERNALDIR=/afs/cern.ch/sw/lcg/app/releases/ROOT-externals/
    if [ "${LABEL_ORG}" == "slc6" ]
    then
	export PATH=/afs/cern.ch/sw/lcg/contrib/CMake/2.8.9/Linux-i386/bin:${PATH}
    fi
else
    export EXTERNALDIR=$HOME/ROOT-externals/
fi

if [[ $COMPILER == *gcc* ]]
then
    gcc47version=4.7
    gcc48version=4.8
    gcc49version=4.9
    COMPILERversion=${COMPILER}version

    ARCH=$(uname -m)

    . /afs/cern.ch/sw/lcg/app/nightlies/${lcg_target}/Tue/gcc/${!COMPILERversion}/${ARCH}-${LABEL}/setup.sh
    . /afs/cern.ch/sw/lcg/app/nightlies/${lcg_target}/Tue/ROOT/${VERSION}/${ARCH}-${LABEL}-${COMPILER}-${V_TYPE}/bin/thisroot.sh


    if [ -d roottest ]; 
    then 
        (cd roottest && git pull); 
    else 
        (git clone http://roottest.cern.ch && cd roottest && git checkout ${VERSION})
    fi

#    cmake roottest
#    ctest -j2
     
fi    

echo "Dumping the full environment ---------------------------------------------------------"
env | sort | sed 's/:/:?     /g' | tr '?' '\n'
echo "--------------------------------------------------------------------------------------"

#---Run the CTest script depending on the compiler------------------------------------------
ctest -VV -S ${THIS}/root-test-slc7_2.cmake


exit 0


