#!/usr/bin/env bash

if [ "${LABEL}" == "slc6" ]; then
  export PATH=/afs/cern.ch/sw/lcg/contrib/CMake/3.0.0/Linux-i386/bin:${PATH}
fi

THIS=$(dirname $0)

#---Run the CTest script-------------------------------------------
ctest -V -S ${THIS}/root-classic.cmake

