#!/usr/bin/env bash

export LC_CTYPE=en_US.UTF-8
export LC_ALL=en_US.UTF-8

#---CMake----------------------------------------------------------
export PATH=/afs/cern.ch/sw/lcg/contrib/CMake/3.0.0/Linux-i386/bin:${PATH}
export EXTERNALDIR=/afs/cern.ch/sw/lcg/app/releases/ROOT-externals/
#---Compiler------------------------------------------------------
ARCH=$(uname -m)
#LABEL="slc6"
. /afs/cern.ch/sw/lcg/contrib/gcc/4.9.0/${ARCH}-${LABEL}/setup.sh
export FC=gfortran
export CXX=`which g++`
export CC=`which gcc`

#------------------------------------------------------------------
THIS=$(dirname $0)

perl ${EXTERNALDIR}${EXTERNALS}/setup.pl -l ${LABEL} -c ${COMPILER} -v opt -t ${EXTERNALS}                                                                         
eval $(${EXTERNALDIR}${EXTERNALS}/setup.pl -l ${LABEL} -c ${COMPILER} -v opt -t ${EXTERNALS})


export ExtraCMakeOptions=";-Droofit=ON;-Dchirp=OFF;-Dhdfs=OFF;-Dbonjour=OFF;-Dfail-on-missing=ON"

 

#---Run the CTest script-------------------------------------------
ctest -VV -S ${THIS}/root-build.cmake 


