#!/usr/bin/env bash

export LC_CTYPE=en_US.UTF-8
export LC_ALL=en_US.UTF-8

#---CMake----------------------------------------------------------
export PATH=/afs/cern.ch/sw/lcg/contrib/CMake/3.0.0/Linux-i386/bin:${PATH}

#---Compiler------------------------------------------------------
ARCH=$(uname -m)
. /afs/cern.ch/sw/lcg/contrib/gcc/4.8.1/${ARCH}-${LABEL}/setup.sh
export FC=gfortran
export CXX=`which g++`
export CC=`which gcc`

#---GSL------------------------------------------------------------
export GSL_DIR=/afs/cern.ch/sw/lcg/external/GSL/1.10/x86_64-slc6-gcc48-opt
export LD_LIBRARY_PATH=${GSL_DIR}/lib:${LD_LIBRARY_PATH}

#---Xrootd---------------------------------------------------------
export XRDSYS=/afs/cern.ch/sw/lcg/external/xrootd/3.2.7/x86_64-slc6-gcc48-opt
export LD_LIBRARY_PATH=${XRDSYS}/lib64:${LD_LIBRARY_PATH}
export PATH=${XRDSYS}/bin:${PATH}

#---Python--------------------------------------------------------
PYTHON_DIR=/afs/cern.ch/sw/lcg/external/Python/2.7.3/x86_64-slc6-gcc48-opt
export PATH=${PYTHON_DIR}/bin:${PATH}
export LD_LIBRARY_PATH=${PYTHON_DIR}/lib:${LD_LIBRARY_PATH}

#---Qt------------------------------------------------------------
export PATH=/afs/cern.ch/sw/lcg/external/qt/4.8.4/x86_64-slc6-gcc48-opt/bin:${PATH}

#---FFTW-----------------------------------------------------------
export FFTW_DIR=/afs/cern.ch/sw/lcg/releases/LCG_68/fftw3/3.1.2/x86_64-slc6-gcc48-opt

#------------------------------------------------------------------
THIS=$(dirname $0)
export ExtraCMakeOptions=";-Droofit=ON;-Dmysql=OFF"

#---Run the CTest script-------------------------------------------
ctest -V -S ${THIS}/root-build.cmake 

