#!/usr/bin/env bash
set -e
set -x

THIS=$(dirname $0)
echo source $THIS/jk-setup.sh $LABEL $COMPILER $BUILDTYPE $EXTERNALS > setup.sh
source $THIS/jk-setup.sh $LABEL $COMPILER $BUILDTYPE $EXTERNALS

if [[ $COMPILER == *clang* ]]
then
    # options specific to SA
    NEW_CLANG_PATH=`pwd`/rootspi/jenkins/StaticAnalysis
    export PATH=$NEW_CLANG_PATH:$PATH
    echo "Exported new clang path: $NEW_CLANG_PATH"
    export SA_CLANG_CPP=`which clang++`
    echo "The clang executable which will be used for the SA is $ $SA_CLANG_CPP"

else
    echo Error: Cannot perform static analysis with compiler $COMPILER
fi

echo "Dumping the full environment ---------------------------------------------------------"
env | sort | sed 's/:/:?     /g' | tr '?' '\n'
echo "--------------------------------------------------------------------------------------"

#---Create stampfile to enable our jenkins to purge old builds------------------------------
touch $WORKSPACE/controlfile

#---Run the CTest script depending on the compiler------------------------------------------
ctest -VV -S ${THIS}/root-build.cmake
build_rc=$?

exit $build_rc
