#!/usr/bin/env bash
set -e -x

# afs_release.sh
# 
# Created by Bertrand Bellenot on 2015/06/25.
# Adjusted to cvmfs by Patricia Mendez Lorenzo on 2016/11/04.
# Copyright 2016 CERN. All rights reserved.
#

# Let's create the directory first in CVMFS

sudo -i -u cvsft<<EOF

# Let's open a transaction unless there is something else already opened
cvmfs_server transaction sft.cern.ch
if [ "\$?" == "1" ]; then
echo "Transaction is already open. Exiting ..."
exit 1                                                                                                                                                                                                                                    
fi

# Let's make the directory for new ROOT version first:

basedir="/cvmfs/sft.cern.ch/lcg/app/releases/ROOT/${ROOTVERSION}"
echo "Value of the basedir: $basedir"
mkdir -p $basedir


if [ ! -d "$basedir" ]; then
  echo 1>&2 "The directory "$basedir" doesn't exist!" >&2
  exit 127
fi

mkdir -p $basedir/${ROOTVERSION}/src
tarfile="root_v${ROOTVERSION}.source.tar.gz"
wget "https://root.cern.ch/download/${tarfile}" >null 2>&1
if [ -f ${tarfile} ]; then
   tar -zxvf ${tarfile} -C $basedir/${ROOTVERSION}/src
   rm ${tarfile}
else
  echo 1>&2 "ERROR: wget https://root.cern.ch/download/${tarfile} failed!" >&2
fi

for var in $(echo ${Configuration} | tr "," " " | tr -d '"')
do
   mkdir -p $basedir/${ROOTVERSION}/$var
   if [ -d "$basedir/${ROOTVERSION}/$var" ]; then
      if [[ $var == *gcc* ]] ; then
         if [[ $var == *cc7* ]] ; then
            FLAVOR="cc7"
         fi
         if [[ $var == *centos7* ]] ; then
            FLAVOR="centos7"
         fi
         if [[ $var == *slc6* ]] ; then
            FLAVOR="slc6"
         fi
         COMPILER=${var%-opt*}    # get the part before "-opt"
         COMPILER=${COMPILER##*-} # get the part after the last '-'
         GCC_VERSION=${COMPILER:0:4}.${COMPILER:4:1}
         tarfile="root_v${ROOTVERSION}.Linux-${FLAVOR}-x86_64-${GCC_VERSION}.tar.gz"
         wget "https://root.cern.ch/download/${tarfile}" >null 2>&1
      fi
      if [[ $var == *mac* ]] ; then
         MAC_VER=${var%-clang*}   # get the part before "-clang"
         MAC_VER=${MAC_VER##*mac} # get the part after "mac"
         MAC_VERSION=${MAC_VER:0:2}.${MAC_VER:2:2}
         CLANG_VER=${var%-opt*}   # get the part before "-opt"
         CLANG_VER=${CLANG_VER##*-} # get the part after the last '-'
         tarfile="root_v${ROOTVERSION}.macosx64-${MAC_VERSION}-${CLANG_VER}.tar.gz"
         wget "https://root.cern.ch/download/${tarfile}" >null 2>&1
      fi
      if [ -f ${tarfile} ]; then
         tar -zxf ${tarfile} -C $basedir/${ROOTVERSION}/$var
         rm ${tarfile}
      else
         echo 1>&2 "ERROR: wget https://root.cern.ch/download/${tarfile} failed!" >&2
      fi
   fi
done

# Let's going to publish it

cd $HOME
cvmfs_server publish sft.cern.ch

EOF


