#!/usr/bin/env bash
#------------------------------------------------------------------
export LC_CTYPE=en_US.UTF-8
export LC_ALL=en_US.UTF-8

#---Set Kerberos --------------------------------------------------
if [ `uname` == "Linux" ]; then
  kinit sftnight@CERN.CH -5 -V -k -t /ec/conf/sftnight.keytab
else
  echo "This is a Mac. No kinit done"
fi

THIS=$(dirname $0)
#---Update Scripts-------------------------------------------------
lockfile -l 60 ${THIS}/svn_update.lock
svn update ${THIS}
rm -f ${THIS}/svn_update.lock



